### PR TITLE
Fix py simple filters module test

### PR DESCRIPTION
**Pull request by jcfr**
With this changes, the test now pass:

```
[...]
569: Testing filter "ZeroCrossingImageFilter" (256 of 258).
569: Testing filter "ZeroFluxNeumannPadImageFilter" (257 of 258).
569: ok
569: 
569: ----------------------------------------------------------------------
569: Ran 1 test in 38.975s
569: 
569: OK
569: Switch to module:  "" 
1/1 Test #569: py_SimpleFiltersModuleTest .......   Passed   62.99 sec

```

### CODE REVIEW

**Comment by blowekamp** [comment]
Thank you for addressing these issues.

The second commit it not the best approach. The STAPLE json file should be deleted instead.

**Comment by jcfr** [comment]
Thanks for reviewing. 77eeae3 removes the faulty json file.

**Comment by jcfr** [comment]
After removing the corresponding json from the build directory, I also confirm the test pass with 77eeae3:

```
569: 
569: ----------------------------------------------------------------------
569: Ran 1 test in 38.504s
569: 
569: OK
569: Switch to module:  "" 
1/1 Test #569: py_SimpleFiltersModuleTest .......   Passed   62.77 sec

```

**Comment by blowekamp** [comment]
The underlying problem has to do with the conversion of std::numeric_traits<int>::max() to int, resulting in some type of value overflow issue. I am not sure how this generates the presented error message.

As I don't believe this filter is fully functional in SimpleFitlers due to lack of an interface for the multi-input filters. Both these issues will need to be addressed to restore this filter.

This looks reasonable for now!
Thanks!

**Pull request merged**
