### PR TITLE
Update cmake_minimum_required to 3.13

### PR DESCRIPTION
**Pull request by phcerdan**
Ref https://github.com/Slicer/Slicer/pull/1095

### CODE REVIEW

**Comment by blowekamp** [comment]
Were you able to try this change locally since ether is no CI?

**Comment by jcfr** [comment]
We are testing locally and also updated the build machine accordingly, we will monitor regression and fix them accordingly.
See https://github.com/Slicer/DashboardScripts/commit/bae66c5188eb4d482e4adadb551ce24405d1e7ee

**Comment by blowekamp** [comment]
Great! @jcfr  I believe you should have merge access.

Related I believe SimpleITK should be update to the current release branch after 1.2.

**Comment by jcfr** [comment]
> I believe SimpleITK should be update to the current release branch after 1.2.

Sounds good. We will add that to the list of todos.

**Pull request merged**
