### PR TITLE
BUG: Fix crash when switching between filters

### PR DESCRIPTION
**Pull request by lassoan**
In Slicer-4.9 (with Qt5), SimpleFilters module made Slicer crash when switching to a widget that contains ctkCoordinatesWidget.
For example, switching to AdaptiveHistogramEqualizationImageFilter and then to another filter caused crash.

The problem was caused by destroying ctkCoordinateWidget while still having connections.

Fixed by removing all connections of filter parameter widgets before the widgets are destroyed.

### CODE REVIEW

**Comment by blowekamp** [comment]
Thanks for the patch. I was off yesterday. Just starting to spin up on this issue...

**Comment by blowekamp** [comment]
@jcfr @lassoan  Was this ever updated in Slicer master?

**Comment by jcfr** [comment]
Not yet. Would be great if someone could take care of it.

I was out at a hackathon last week and now in vacation.

**Comment by lassoan** [comment]
Fixed in rev 27138.

The update has fixed py_SimpleFiltersModuleTest, which has been failing for a long time.

**Comment by blowekamp** [comment]
Thanks again to fixing this. I still don't understand the origins of this problem and where the behavior changed.

I thought that with Qt slot and signals, when were automatically deleted when the QtObject emitting the signal was deconstructed. So the need for this fix just seems little odd to me and makes me thing there may be something improper with the destructor of the  ctkCoordinateWidget.

**Comment by lassoan** [comment]
I don't understand the root cause either and why the problem is only with ctkCoordinateWidget. The issue came up when we switched to Qt5.

**Pull request merged**
